### ISSUE TITLE
Crear rutas /ligas y /equipos

### ISSUE THREAD

**Issue by Joacz** [Joacz/FootStats#14]
### Se necesitan crear los directorios y archivos para las rutas /ligas /equipos
las cuales mostraran todas las entidades de ambas clases _(equipo y liga)_
 
![image](https://user-images.githubusercontent.com/97977119/203810304-19058bf7-6ee7-4f8c-84f2-4650e45cd7ec.png)

Gracias!

**Comment by kev-tsx** [comment]
Rutas creadas

**Comment by kev-rs** [comment]
Rutas creadas
